import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.Rectangle;

import javax.management.RuntimeOperationsException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.ScrollBarUI;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JScrollPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Scrollbar;
import java.awt.ComponentOrientation;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;


public class ForExe1 extends javax.swing.JFrame {

    /**
     * Creates new form ForExe1
     */
	String textParaArea;
	JTextArea JTEXTAREA9 = new JTextArea();
	JScrollPane PscrollPane=new JScrollPane();
	
	
    
	
	
    public ForExe1() {
    	setTitle("LABORATORIO DE PROGRAMA\u00C7\u00C3O 2 - EXERCICIOS");    	
    	JTEXTAREA9.add(PscrollPane);
    	JTEXTAREA9.setAutoscrolls(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNUM1 = new javax.swing.JTextField();
        jTNUM2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTDIVISAO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTMULTIPLICACAO = new javax.swing.JTextField();
        jTADICAO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTSUBTRACAO = new javax.swing.JTextField();
        jBEXECUTAR = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTCTNUM1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTCTRESULTADO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTCTNUM2 = new javax.swing.JTextField();
        jBEXECUTAR2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jTRESULTADO3 = new javax.swing.JTextField();
        jBEXECUTAR3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jTNUM4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTRESULTADO4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBEXECUTAR4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jTNUM5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTRESULTADO5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jBEXECUTAR5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jTNUME6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTRESULTADO6_2 = new javax.swing.JTextField();
        jBEXECUTAR6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jTNUM7_1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTRESULTADOE7 = new javax.swing.JTextField();
        jTNUM7_2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTNUM7_3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jTNUM8_1 = new javax.swing.JTextField();
        jTRESULTADO8 = new javax.swing.JTextField();
        jTNUM8_2 = new javax.swing.JTextField();
        jTNUM8_3 = new javax.swing.JTextField();
        jTNUM8_4 = new javax.swing.JTextField();
        jTNUM8_5 = new javax.swing.JTextField();
        jTNUM8_6 = new javax.swing.JTextField();
        jTNUM8_7 = new javax.swing.JTextField();
        jTNUM8_8 = new javax.swing.JTextField();
        jTNUM8_9 = new javax.swing.JTextField();
        jTNUM8_10 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel15.setLocation(-30, -66);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("DIGITE DOIS NUMEROS INTEIROS:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTNUM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTNUM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jLabel3.setText("Subtração:");

        jTDIVISAO.setEditable(false);
        jTDIVISAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setText("Divisão:");

        jLabel5.setText("Multiplicação:");

        jTMULTIPLICACAO.setEditable(false);
        jTMULTIPLICACAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTADICAO.setEditable(false);
        jTADICAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setText("Adição:");

        jTSUBTRACAO.setEditable(false);
        jTSUBTRACAO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTADICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTSUBTRACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTDIVISAO, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTMULTIPLICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTADICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTSUBTRACAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDIVISAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMULTIPLICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jBEXECUTAR.setText("EXECUTAR");
        jBEXECUTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jBEXECUTAR)))
                .addGap(0, 121, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jBEXECUTAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("1", jPanel4);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Calcula a area do triangulo"));

        jLabel6.setText(" BASE");

        jTCTRESULTADO.setEditable(false);
        jTCTRESULTADO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel7.setText("ALTURA");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTCTNUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTCTNUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTCTRESULTADO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCTNUM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCTNUM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jTCTRESULTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jBEXECUTAR2.setText("EXECUTAR");
        jBEXECUTAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTAR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jBEXECUTAR2)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEXECUTAR2)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("2", jPanel6);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Orçamento de Materiais"));

        jTRESULTADO3.setEditable(false);
        jTRESULTADO3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTRESULTADO3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTRESULTADO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jBEXECUTAR3.setText("EXECUTAR");
        jBEXECUTAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTAR3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBEXECUTAR3)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEXECUTAR3)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("3", jPanel7);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Imprimir quadrado"));

        jLabel8.setText("NUMERO:");

        jTRESULTADO4.setEditable(false);
        jTRESULTADO4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setText("QUADRADO:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTNUM4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTRESULTADO4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNUM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(50, 50, 50)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRESULTADO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jBEXECUTAR4.setText("EXECUTAR");
        jBEXECUTAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTAR4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBEXECUTAR4)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEXECUTAR4)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("4", jPanel8);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Converter para Fahrenheit"));

        jLabel10.setText("CELSIUS");

        jTRESULTADO5.setEditable(false);
        jTRESULTADO5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setText("FAHRENHEIT");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTNUM5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTRESULTADO5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNUM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(50, 50, 50)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRESULTADO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jBEXECUTAR5.setText("EXECUTAR");
        jBEXECUTAR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTAR5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBEXECUTAR5)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEXECUTAR5)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("5", jPanel9);

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Positivo ou Negativo"));

        jLabel16.setText("NUMERO:");

        jTRESULTADO6_2.setEditable(false);
        jTRESULTADO6_2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTRESULTADO6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTNUME6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNUME6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(50, 50, 50)
                .addComponent(jTRESULTADO6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jBEXECUTAR6.setText("EXECUTAR");
        jBEXECUTAR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTAR6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10Layout.setHorizontalGroup(
        	jPanel10Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel10Layout.createSequentialGroup()
        			.addGap(32)
        			.addGroup(jPanel10Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jBEXECUTAR6)
        				.addComponent(jPanel22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
        	jPanel10Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel10Layout.createSequentialGroup()
        			.addGap(27)
        			.addComponent(jPanel22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jBEXECUTAR6)
        			.addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel10.setLayout(jPanel10Layout);

        jTabbedPane2.addTab("6", jPanel10);

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder("Aluno Aprovado ou Reprovado"));

        jLabel17.setText("MEDIA 1");

        jTRESULTADOE7.setEditable(false);
        jTRESULTADOE7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel19.setText("MEDIA 2");

        jLabel20.setText("MEDIA 3");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23Layout.setHorizontalGroup(
        	jPanel23Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel23Layout.createSequentialGroup()
        			.addContainerGap(90, Short.MAX_VALUE)
        			.addGroup(jPanel23Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel23Layout.createSequentialGroup()
        					.addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jTNUM7_1, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel23Layout.createSequentialGroup()
        					.addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jTNUM7_2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel23Layout.createSequentialGroup()
        					.addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jTNUM7_3, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jTRESULTADOE7, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
        	jPanel23Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel23Layout.createSequentialGroup()
        			.addGap(26)
        			.addGroup(jPanel23Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTNUM7_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel17))
        			.addGap(11)
        			.addGroup(jPanel23Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTNUM7_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel19))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel23Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTNUM7_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel20))
        			.addGap(18)
        			.addComponent(jTRESULTADOE7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel23.setLayout(jPanel23Layout);
        
        jBEXECUTAR7 = new JButton();
        jBEXECUTAR7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Media();
        	}
        });
        jBEXECUTAR7.setText("EXECUTAR");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11Layout.setHorizontalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addGap(25)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel23, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jBEXECUTAR7, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addGap(36)
        			.addComponent(jPanel23, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jBEXECUTAR7)
        			.addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel11.setLayout(jPanel11Layout);

        jTabbedPane2.addTab("7", jPanel11);

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder("Maior Numero"));

        jTRESULTADO8.setEditable(false);
        jTRESULTADO8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24Layout.setHorizontalGroup(
        	jPanel24Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jTNUM8_4, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTNUM8_5, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTNUM8_1, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTNUM8_2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTNUM8_3, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jTNUM8_9, GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        				.addComponent(jTNUM8_10, GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        				.addComponent(jTNUM8_7, GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        				.addComponent(jTNUM8_8, GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        				.addComponent(jTNUM8_6, GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        				.addComponent(jTRESULTADO8))
        			.addGap(49))
        );
        jPanel24Layout.setVerticalGroup(
        	jPanel24Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel24Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel24Layout.createSequentialGroup()
        					.addComponent(jTNUM8_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(11)
        					.addComponent(jTNUM8_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jTNUM8_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jTNUM8_4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(11)
        					.addComponent(jTNUM8_5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel24Layout.createSequentialGroup()
        					.addComponent(jTNUM8_6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(11)
        					.addGroup(jPanel24Layout.createSequentialGroup()
        						.addComponent(jTNUM8_7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.UNRELATED)
        						.addComponent(jTNUM8_8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(jTNUM8_9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGap(11)
        						.addComponent(jTNUM8_10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addPreferredGap(ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
        			.addComponent(jTRESULTADO8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel24.setLayout(jPanel24Layout);
        
        jBEXECUTAR8 = new JButton();
        jBEXECUTAR8.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Maior();
        	}
        });
        jBEXECUTAR8.setText("EXECUTAR");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12Layout.setHorizontalGroup(
        	jPanel12Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel12Layout.createSequentialGroup()
        			.addGroup(jPanel12Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(Alignment.LEADING, jPanel12Layout.createSequentialGroup()
        					.addGap(25)
        					.addComponent(jPanel24, 0, 0, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, jPanel12Layout.createSequentialGroup()
        					.addGap(187)
        					.addComponent(jBEXECUTAR8, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
        	jPanel12Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel12Layout.createSequentialGroup()
        			.addGap(36)
        			.addComponent(jPanel24, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jBEXECUTAR8)
        			.addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel12.setLayout(jPanel12Layout);

        jTabbedPane2.addTab("8", jPanel12);
        
        jpanel25 = new JPanel();        
        jpanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Imprime 10 x"));
        
        jBEXECUTAR9 = new JButton();
        jBEXECUTAR9.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Imprime10();
        	}
        });
        jBEXECUTAR9.setText("EXECUTAR");
        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13Layout.setHorizontalGroup(
        	jPanel13Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel13Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel13Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jBEXECUTAR9, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jpanel25, GroupLayout.PREFERRED_SIZE, 405, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
        	jPanel13Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel13Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpanel25, GroupLayout.PREFERRED_SIZE, 264, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jBEXECUTAR9)
        			.addContainerGap(84, Short.MAX_VALUE))
        );
        jpanel25.setLayout(null);
        
                
        JTEXTAREA9.setBounds(20, 73, 364, 183);
        JTEXTAREA9.setText(textParaArea);
        jpanel25.add(JTEXTAREA9);
        
        jTNUM9 = new JTextField();
        jTNUM9.setBounds(20, 35, 364, 27);
        jpanel25.add(jTNUM9);
        jPanel13.setLayout(jPanel13Layout);

        jTabbedPane2.addTab("9", jPanel13);
        
        jpanel26 = new JPanel();
        jpanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Lucro 45% ou 30%"));
        
        jBEXECUTAR10 = new JButton();
        jBEXECUTAR10.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Lucro();
        	}
        });
        jBEXECUTAR10.setText("EXECUTAR");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14Layout.setHorizontalGroup(
        	jPanel14Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel14Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel14Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jBEXECUTAR10, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jpanel26, GroupLayout.PREFERRED_SIZE, 346, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
        	jPanel14Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel14Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpanel26, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jBEXECUTAR10)
        			.addContainerGap(181, Short.MAX_VALUE))
        );
        jpanel26.setLayout(null);
        
        jTNUM10 = new JTextField();
        jTNUM10.setBounds(137, 29, 117, 28);
        jpanel26.add(jTNUM10);
        
        JLabel lblValorDaCompra = new JLabel();
        lblValorDaCompra.setText("VALOR DA COMPRA");
        lblValorDaCompra.setBounds(10, 36, 117, 14);
        jpanel26.add(lblValorDaCompra);
        
        lblValorDaVenda = new JLabel();
        lblValorDaVenda.setText("VALOR DA VENDA");
        lblValorDaVenda.setBounds(10, 75, 117, 14);
        jpanel26.add(lblValorDaVenda);
        
        jTRESULTADO10 = new JTextField();
        jTRESULTADO10.setEditable(false);
        jTRESULTADO10.setBounds(137, 68, 117, 28);
        jpanel26.add(jTRESULTADO10);
        jPanel14.setLayout(jPanel14Layout);

        jTabbedPane2.addTab("10", jPanel14);
        
        jpanel27 = new JPanel();
        jpanel27.setBorder(javax.swing.BorderFactory.createTitledBorder("Maior idade"));
        
        jBEXECUTAR11 = new JButton();
        jBEXECUTAR11.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		MaiorIdade();
        	}
        });
        jBEXECUTAR11.setText("EXECUTAR");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15Layout.setHorizontalGroup(
        	jPanel15Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
        			.addGroup(jPanel15Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel15Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jBEXECUTAR11, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel15Layout.createSequentialGroup()
        					.addGap(28)
        					.addComponent(jpanel27, GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
        			.addGap(34))
        );
        jPanel15Layout.setVerticalGroup(
        	jPanel15Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel15Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpanel27, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jBEXECUTAR11)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel27.setLayout(null);
        
        label = new JLabel();
        label.setText("1\u00AA:");
        label.setBounds(10, 45, 15, 14);
        jpanel27.add(label);
        
        jTNUM11_1 = new JTextField();
        jTNUM11_1.setBounds(33, 38, 117, 28);
        jpanel27.add(jTNUM11_1);
        
        label_1 = new JLabel();
        label_1.setText("2\u00AA:");
        label_1.setBounds(10, 77, 15, 14);
        jpanel27.add(label_1);
        
        jTNUM11_2 = new JTextField();
        jTNUM11_2.setBounds(33, 70, 117, 28);
        jpanel27.add(jTNUM11_2);
        
        label_2 = new JLabel();
        label_2.setText("3\u00AA:");
        label_2.setBounds(10, 109, 15, 14);
        jpanel27.add(label_2);
        
        jTNUM11_3 = new JTextField();
        jTNUM11_3.setBounds(33, 102, 117, 28);
        jpanel27.add(jTNUM11_3);
        
        label_3 = new JLabel();
        label_3.setText("4\u00AA:");
        label_3.setBounds(10, 141, 15, 14);
        jpanel27.add(label_3);
        
        jTNUM11_4 = new JTextField();
        jTNUM11_4.setBounds(33, 134, 117, 28);
        jpanel27.add(jTNUM11_4);
        
        label_4 = new JLabel();
        label_4.setText("5\u00AA:");
        label_4.setBounds(10, 173, 15, 14);
        jpanel27.add(label_4);
        
        jTNUM11_5 = new JTextField();
        jTNUM11_5.setBounds(33, 166, 117, 28);
        jpanel27.add(jTNUM11_5);
        
        label_5 = new JLabel();
        label_5.setText("6\u00AA:");
        label_5.setBounds(10, 205, 15, 14);
        jpanel27.add(label_5);
        
        jTNUM11_6 = new JTextField();
        jTNUM11_6.setBounds(33, 198, 117, 28);
        jpanel27.add(jTNUM11_6);
        
        label_6 = new JLabel();
        label_6.setText("7\u00AA:");
        label_6.setBounds(10, 238, 15, 14);
        jpanel27.add(label_6);
        
        jTNUM11_7 = new JTextField();
        jTNUM11_7.setBounds(33, 231, 117, 28);
        jpanel27.add(jTNUM11_7);
        
        jTNUM11_14 = new JTextField();
        jTNUM11_14.setBounds(198, 231, 117, 28);
        jpanel27.add(jTNUM11_14);
        
        jTNUM11_13 = new JTextField();
        jTNUM11_13.setBounds(198, 198, 117, 28);
        jpanel27.add(jTNUM11_13);
        
        jTNUM11_12 = new JTextField();
        jTNUM11_12.setBounds(198, 166, 117, 28);
        jpanel27.add(jTNUM11_12);
        
        jTNUM11_11 = new JTextField();
        jTNUM11_11.setBounds(198, 134, 117, 28);
        jpanel27.add(jTNUM11_11);
        
        jTNUM11_10 = new JTextField();
        jTNUM11_10.setBounds(198, 102, 117, 28);
        jpanel27.add(jTNUM11_10);
        
        label_12 = new JLabel();
        label_12.setHorizontalAlignment(SwingConstants.RIGHT);
        label_12.setText("10\u00AA:");
        label_12.setBounds(164, 109, 26, 14);
        jpanel27.add(label_12);
        
        jTNUM11_9 = new JTextField();
        jTNUM11_9.setBounds(198, 70, 117, 28);
        jpanel27.add(jTNUM11_9);
        
        jTNUM11_8 = new JTextField();
        jTNUM11_8.setBounds(198, 38, 117, 28);
        jpanel27.add(jTNUM11_8);
        
        jTNUM11_15 = new JTextField();
        jTNUM11_15.setBounds(367, 38, 117, 28);
        jpanel27.add(jTNUM11_15);
        
        jTNUM11_16 = new JTextField();
        jTNUM11_16.setBounds(367, 70, 117, 28);
        jpanel27.add(jTNUM11_16);
        
        jTNUM11_17 = new JTextField();
        jTNUM11_17.setBounds(367, 102, 117, 28);
        jpanel27.add(jTNUM11_17);
        
        jTNUM11_18 = new JTextField();
        jTNUM11_18.setBounds(367, 134, 117, 28);
        jpanel27.add(jTNUM11_18);
        
        jTNUM11_19 = new JTextField();
        jTNUM11_19.setBounds(367, 166, 117, 28);
        jpanel27.add(jTNUM11_19);
        
        jTNUM11_20 = new JTextField();
        jTNUM11_20.setBounds(367, 198, 117, 28);
        jpanel27.add(jTNUM11_20);
        
        label_8 = new JLabel();
        label_8.setText("8\u00AA:");
        label_8.setHorizontalAlignment(SwingConstants.RIGHT);
        label_8.setBounds(164, 45, 26, 14);
        jpanel27.add(label_8);
        
        label_9 = new JLabel();
        label_9.setText("9\u00AA:");
        label_9.setHorizontalAlignment(SwingConstants.RIGHT);
        label_9.setBounds(164, 77, 26, 14);
        jpanel27.add(label_9);
        
        label_10 = new JLabel();
        label_10.setText("11\u00AA:");
        label_10.setHorizontalAlignment(SwingConstants.RIGHT);
        label_10.setBounds(162, 141, 26, 14);
        jpanel27.add(label_10);
        
        label_11 = new JLabel();
        label_11.setText("12\u00AA:");
        label_11.setHorizontalAlignment(SwingConstants.RIGHT);
        label_11.setBounds(162, 173, 26, 14);
        jpanel27.add(label_11);
        
        label_13 = new JLabel();
        label_13.setText("13\u00AA:");
        label_13.setHorizontalAlignment(SwingConstants.RIGHT);
        label_13.setBounds(162, 205, 26, 14);
        jpanel27.add(label_13);
        
        label_14 = new JLabel();
        label_14.setText("14\u00AA:");
        label_14.setHorizontalAlignment(SwingConstants.RIGHT);
        label_14.setBounds(162, 238, 26, 14);
        jpanel27.add(label_14);
        
        label_7 = new JLabel();
        label_7.setText("15\u00AA:");
        label_7.setHorizontalAlignment(SwingConstants.RIGHT);
        label_7.setBounds(331, 45, 26, 14);
        jpanel27.add(label_7);
        
        label_15 = new JLabel();
        label_15.setText("16\u00AA:");
        label_15.setHorizontalAlignment(SwingConstants.RIGHT);
        label_15.setBounds(331, 77, 26, 14);
        jpanel27.add(label_15);
        
        label_16 = new JLabel();
        label_16.setText("17\u00AA:");
        label_16.setHorizontalAlignment(SwingConstants.RIGHT);
        label_16.setBounds(331, 109, 26, 14);
        jpanel27.add(label_16);
        
        label_17 = new JLabel();
        label_17.setText("18\u00AA:");
        label_17.setHorizontalAlignment(SwingConstants.RIGHT);
        label_17.setBounds(329, 141, 26, 14);
        jpanel27.add(label_17);
        
        label_18 = new JLabel();
        label_18.setText("19\u00AA:");
        label_18.setHorizontalAlignment(SwingConstants.RIGHT);
        label_18.setBounds(329, 173, 26, 14);
        jpanel27.add(label_18);
        
        label_19 = new JLabel();
        label_19.setText("20\u00AA:");
        label_19.setHorizontalAlignment(SwingConstants.RIGHT);
        label_19.setBounds(329, 205, 26, 14);
        jpanel27.add(label_19);
        
        jTRESULTADO11_1 = new JTextField();
        jTRESULTADO11_1.setFont(new Font("Tahoma", Font.BOLD, 11));
        jTRESULTADO11_1.setEditable(false);
        jTRESULTADO11_1.setBounds(396, 256, 88, 30);
        jpanel27.add(jTRESULTADO11_1);
        
        lblQdtDeMaiores = new JLabel();
        lblQdtDeMaiores.setHorizontalAlignment(SwingConstants.RIGHT);
        lblQdtDeMaiores.setText("QDT DE MAIORES DE 18:");
        lblQdtDeMaiores.setBounds(255, 262, 131, 27);
        jpanel27.add(lblQdtDeMaiores);
        
        jTRESULTADO11_2 = new JTextField();
        jTRESULTADO11_2.setFont(new Font("Tahoma", Font.BOLD, 11));
        jTRESULTADO11_2.setEditable(false);
        jTRESULTADO11_2.setBounds(396, 297, 88, 30);
        jpanel27.add(jTRESULTADO11_2);
        
        lblIdadeMaisAvanada = new JLabel();
        lblIdadeMaisAvanada.setHorizontalAlignment(SwingConstants.RIGHT);
        lblIdadeMaisAvanada.setText("IDADE MAIS AVAN\u00C7ADA: ");
        lblIdadeMaisAvanada.setBounds(242, 300, 144, 27);
        jpanel27.add(lblIdadeMaisAvanada);
        jPanel15.setLayout(jPanel15Layout);

        jTabbedPane2.addTab("11", jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTabbedPane2, GroupLayout.PREFERRED_SIZE, 561, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jTabbedPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEXECUTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTARActionPerformed
        // TODO add your handling code here:
    	Operacoes();
    }//GEN-LAST:event_jBEXECUTARActionPerformed

    private void jBEXECUTAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTAR2ActionPerformed
        // TODO add your handling code here:
        Areatriangulo();
    }//GEN-LAST:event_jBEXECUTAR2ActionPerformed

    private void jBEXECUTAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTAR3ActionPerformed
        // TODO add your handling code here:
        Orcamento();
    }//GEN-LAST:event_jBEXECUTAR3ActionPerformed

    private void jBEXECUTAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTAR4ActionPerformed
        // TODO add your handling code here
        Quadrado();
    }//GEN-LAST:event_jBEXECUTAR4ActionPerformed

    private void jBEXECUTAR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTAR5ActionPerformed
        // TODO add your handling code here:
        ConverteF();
    }//GEN-LAST:event_jBEXECUTAR5ActionPerformed

    private void jBEXECUTAR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTAR6ActionPerformed
        // TODO add your handling code here:
        PosNegativo();
        
    }//GEN-LAST:event_jBEXECUTAR6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForExe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForExe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForExe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForExe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForExe1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEXECUTAR;
    private javax.swing.JButton jBEXECUTAR2;
    private javax.swing.JButton jBEXECUTAR3;
    private javax.swing.JButton jBEXECUTAR4;
    private javax.swing.JButton jBEXECUTAR5;
    private javax.swing.JButton jBEXECUTAR6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTADICAO;
    private javax.swing.JTextField jTCTNUM1;
    private javax.swing.JTextField jTCTNUM2;
    private javax.swing.JTextField jTCTRESULTADO;
    private javax.swing.JTextField jTDIVISAO;
    private javax.swing.JTextField jTMULTIPLICACAO;
    private javax.swing.JTextField jTNUM1;
    private javax.swing.JTextField jTNUM2;
    private javax.swing.JTextField jTNUM4;
    private javax.swing.JTextField jTNUM5;
    private javax.swing.JTextField jTNUM6;
    private javax.swing.JTextField jTNUM7;
    private javax.swing.JTextField jTNUM7_1;
    private javax.swing.JTextField jTNUM7_2;
    private javax.swing.JTextField jTNUM7_3;
    private javax.swing.JTextField jTNUM8_1;
    private javax.swing.JTextField jTNUM8_10;
    private javax.swing.JTextField jTNUM8_2;
    private javax.swing.JTextField jTNUM8_3;
    private javax.swing.JTextField jTNUM8_4;
    private javax.swing.JTextField jTNUM8_5;
    private javax.swing.JTextField jTNUM8_6;
    private javax.swing.JTextField jTNUM8_7;
    private javax.swing.JTextField jTNUM8_8;
    private javax.swing.JTextField jTNUM8_9;
    private javax.swing.JTextField jTNUME6;
    private javax.swing.JTextField jTRESULTADO3;
    private javax.swing.JTextField jTRESULTADO4;
    private javax.swing.JTextField jTRESULTADO5;
    private javax.swing.JTextField jTRESULTADO6;
    private javax.swing.JTextField jTRESULTADO7;
    private javax.swing.JTextField jTRESULTADO6_2;
    private javax.swing.JTextField jTRESULTADOE7;
    private javax.swing.JTextField jTRESULTADO8;
    private javax.swing.JTextField jTSUBTRACAO;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private JButton jBEXECUTAR7;
    private JButton jBEXECUTAR8;
    private JPanel jpanel25;
    private JButton jBEXECUTAR9;
    private JTextField jTNUM9;
    private JPanel jpanel26;
    private JTextField jTNUM10;
    private JLabel lblValorDaVenda;
    private JTextField jTRESULTADO10;
    private JButton jBEXECUTAR10;
    private JPanel jpanel27;
    private JLabel label;
    private JTextField jTNUM11_1;
    private JLabel label_1;
    private JTextField jTNUM11_2;
    private JLabel label_2;
    private JTextField jTNUM11_3;
    private JLabel label_3;
    private JTextField jTNUM11_4;
    private JLabel label_4;
    private JTextField jTNUM11_5;
    private JLabel label_5;
    private JTextField jTNUM11_6;
    private JLabel label_6;
    private JTextField jTNUM11_7;
    private JTextField jTNUM11_14;
    private JTextField jTNUM11_13;
    private JTextField jTNUM11_12;
    private JTextField jTNUM11_11;
    private JTextField jTNUM11_10;
    private JLabel label_12;
    private JTextField jTNUM11_9;
    private JTextField jTNUM11_8;
    private JTextField jTNUM11_15;
    private JTextField jTNUM11_16;
    private JTextField jTNUM11_17;
    private JTextField jTNUM11_18;
    private JTextField jTNUM11_19;
    private JTextField jTNUM11_20;
    private JLabel label_8;
    private JLabel label_9;
    private JLabel label_10;
    private JLabel label_11;
    private JLabel label_13;
    private JLabel label_14;
    private JLabel label_7;
    private JLabel label_15;
    private JLabel label_16;
    private JLabel label_17;
    private JLabel label_18;
    private JLabel label_19;
    private JTextField jTRESULTADO11_1;
    private JLabel lblQdtDeMaiores;
    private JTextField jTRESULTADO11_2;
    private JLabel lblIdadeMaisAvanada;
    private JButton jBEXECUTAR11;
    // End of variables declaration//GEN-END:variables

    /*exercicio 1*/
    private void Operacoes(){
        int Result;
        int varnum1;
        int varnum2;
        varnum1 = 0;
        varnum2 = 0;
        if(!jTNUM1.getText().equals("")){
        	varnum1 = Integer.parseInt(jTNUM1.getText());
        }else{
        	jTNUM1.setText("0");
        }
        if(!jTNUM2.getText().equals("")){
        	varnum2 = Integer.parseInt(jTNUM2.getText());
        }else{
        	jTNUM2.setText("0");
        }
        
        try{
        Result = varnum1 / varnum2;
        }catch(ArithmeticException e){
        	Result = 0;
        }
        jTDIVISAO.setText(String.valueOf(Result));
        Result = varnum1 * varnum2;        
        jTMULTIPLICACAO.setText(String.valueOf(Result));
        Result = varnum1 - varnum2;        
        jTSUBTRACAO.setText(String.valueOf(Result));
        Result = varnum1 + varnum2;        
        jTADICAO.setText(String.valueOf(Result));
        
    }    
    /*fim exercicio 1*/
    
    /*exercicio 2*/    
    private void Areatriangulo(){
        double Result;
        double varnum1;
        double varnum2;
        varnum1 = 0;
        varnum2 = 0;
        if(!jTCTNUM1.getText().equals("")){        
        	varnum1 = Double.parseDouble(jTCTNUM1.getText());        	
        }else{
        	jTCTNUM1.setText("0");
        }
        if(!jTCTNUM2.getText().equals("")){        
        	varnum2 = Double.parseDouble(jTCTNUM2.getText());        	
        }else{
        	jTCTNUM2.setText("0");
        }        
        Result = (varnum1 * varnum2)/2;        
        jTCTRESULTADO.setText(String.valueOf(Result));        
    }
    /*fim exercicio 2*/
    
    /*exercicio 3*/    
    private void Orcamento(){
        double Result;
        double cadernos;
        double canetas;
        double regua;
        double calculadora;
        cadernos = 1.50 * 7;
        canetas = 0.25 * 2;
        regua = 0.15;
        calculadora = 5.5;                
        Result = (cadernos + canetas + regua + calculadora);       
        jTRESULTADO3.setText(String.valueOf(Result));        
    }
    /*fim exercicio 3*/
    
    /*exercicio 4*/    
    private void Quadrado(){
        double Result;
        double num1;
        num1 = 0;
        if(!jTNUM4.getText().equals("")){        	
        	num1 = Double.parseDouble(jTNUM4.getText());
        }        
        Result = num1* num1;  
        		//(Math.sqrt(num1));       
        jTRESULTADO4.setText(String.valueOf(Result));        
    }
    /*fim exercicio 4*/
    
    /*exercicio 5*/    
    private void ConverteF(){
        double Result;
        double num1;
        num1 = 0;
        if(!jTNUM5.getText().equals("")){
        	num1 = Double.parseDouble(jTNUM5.getText());
        }        
        Result = (9.0 * num1 +160.0)/5;       
        jTRESULTADO5.setText(String.valueOf(Result));        
    }
    /*fim exercicio 5*/
    
    
    /*exercicio 6*/    
    private void PosNegativo(){
        String Result2;
        double num1;
        num1 = 0;
        if(!jTNUME6.getText().equals("") ){
        	num1 = Double.parseDouble(jTNUME6.getText());	
        }     
        if (num1 < 0){
            Result2 = "NUMERO NEGATIVO";
        }
        else{
            Result2 = "NUMERO POSITIVO";
            if (num1 == 0){
            	jTNUME6.setText("0");             
            }
        }        
        jTRESULTADO6_2.setText(Result2);        
    }
    /*fim exercicio 6*/  
    
    
    
    /*exercicio 7*/
    
	private void Media(){
        String Result;
        double num1;
        double num2;
        double num3;
        double finmedia;
        num1 = 0;
        num2 = 0;
        num3 = 0;           
        if(!jTNUM7_1.getText().equals("") ){
        	num1 = Double.parseDouble(jTNUM7_1.getText());
        }else{
        	jTNUM7_1.setText("0");
        }
        if(!jTNUM7_2.getText().equals("") ){
        	num2 = Double.parseDouble(jTNUM7_2.getText());
        }else{
        	jTNUM7_2.setText("0");
        }
        if(!jTNUM7_3.getText().equals("") ){
        	num3 = Double.parseDouble(jTNUM7_3.getText());
        }else{
        	jTNUM7_3.setText("0");
        }      
        
        finmedia =  (num1 + num2 + num3) / 3;        
        if (finmedia < 6){
            Result = "ALUNO REPROVADO";
        }else{
            Result = "ALUNO APROVADO";
        }        
        jTRESULTADOE7.setText(Result);        
    }
    /*fim exercicio 7*/
    
    /*exercicio 8*/    
    private void Maior(){
        double[] num;
        num = new double[10];        
        double Result;
        Result = 0;        
        for(int i=0; i < 10; i++){
        	num[i] = 0;        	
        }        
        if(!jTNUM8_1.getText().equals("") ){
        	num[0] = Double.parseDouble(jTNUM8_1.getText());               	
        }else{
        	jTNUM8_1.setText(String.valueOf(num[0]));
        }
        
        if(!jTNUM8_2.getText().equals("") ){
        	num[1] = Double.parseDouble(jTNUM8_2.getText());
        }else{
        	jTNUM8_2.setText(String.valueOf(num[1]));
        }
        if(!jTNUM8_3.getText().equals("") ){
        	num[2] = Double.parseDouble(jTNUM8_3.getText());
        }else{
        	jTNUM8_3.setText(String.valueOf(num[2]));
        }
        
        if(!jTNUM8_4.getText().equals("") ){
        	num[3] = Double.parseDouble(jTNUM8_4.getText());
        }else{
        	jTNUM8_4.setText(String.valueOf(num[3]));
        }
        
        if(!jTNUM8_5.getText().equals("") ){
        	num[4] = Double.parseDouble(jTNUM8_5.getText());
        }else{
        	jTNUM8_5.setText(String.valueOf(num[4]));
        }
        
        if(!jTNUM8_6.getText().equals("") ){
        	num[5] = Double.parseDouble(jTNUM8_6.getText());       	
        }else{
        	jTNUM8_6.setText(String.valueOf(num[5]));
        }
        
        if(!jTNUM8_7.getText().equals("") ){
        	num[6] = Double.parseDouble(jTNUM8_7.getText());
        }else{
        	jTNUM8_7.setText(String.valueOf(num[6]));
        }
        if(!jTNUM8_8.getText().equals("") ){
        	num[7] = Double.parseDouble(jTNUM8_8.getText());
        }else{
        	jTNUM8_8.setText(String.valueOf(num[7]));
        }
        
        if(!jTNUM8_9.getText().equals("") ){
        	num[8] = Double.parseDouble(jTNUM8_9.getText());
        }else{
        	jTNUM8_9.setText(String.valueOf(num[8]));
        }
        
        if(!jTNUM8_10.getText().equals("") ){
        	num[9] = Double.parseDouble(jTNUM8_10.getText());
        }else{
        	jTNUM8_10.setText(String.valueOf(num[9]));
        }
        
        for(int i=0; i < 10; i++){
        	if(Result < num[i] ){
        		Result = num[i];        		
        	}
        }
        jTRESULTADO8.setText(String.valueOf(Result));        
    }
    /*fim exercicio 8*/
    /*exercicio 9*/    
    private void Imprime10(){    	
    	String paraImprimir;
    	paraImprimir = "";
    	//paraImprimir =jTNUM9.getText();
    	for(int i =0; i < 10; i++){
    		if(i==0){
    		paraImprimir = jTNUM9.getText();
    		}else{
    			paraImprimir = paraImprimir +"\n"+ jTNUM9.getText();
    		}
    	}    	
    	JTEXTAREA9.setText(paraImprimir);    	
    }
    
    /*fim exercicio 9*/    
    /*exercicio 10*/
    private void Lucro(){
    	double num1;
    	num1 = 0;
    	if(!jTNUM10.getText().equals("") ){    		
    		num1 = Double.parseDouble(jTNUM10.getText());
    	}else{
    		jTNUM10.setText(String.valueOf(num1));    		
    	}
    	if(num1 <= 20){
    		num1 = num1 + (num1* 0.45);
    	}else{
    		num1 = num1 + (num1 * 0.30);
    	}    	
    	jTRESULTADO10.setText(String.valueOf(num1));
    }
    /*fim exercicio 10*/
    /*exercicio 11*/
    private void MaiorIdade(){
    	double[] num;
        num = new double[20];        
        double maior;
        int cont;
        maior = 0;
        cont =0;
        for(int i=0; i < 10; i++){
        	num[i] = 0;        	
        }
        
        if(!jTNUM11_1.getText().equals("") ){
        	num[0] = Double.parseDouble(jTNUM11_1.getText());
        }else{
        	jTNUM11_1.setText("0");
        }
        
        if(!jTNUM11_2.getText().equals("") ){
        	num[1] = Double.parseDouble(jTNUM11_2.getText());
        }else{
        	jTNUM11_2.setText("0");
        }     
        
        if(!jTNUM11_3.getText().equals("") ){
        	num[2] = Double.parseDouble(jTNUM11_3.getText());
        }else{
        	jTNUM11_1.setText("0");
        }
        
        if(!jTNUM11_4.getText().equals("") ){
        	num[3] = Double.parseDouble(jTNUM11_4.getText());
        }else{
        	jTNUM11_4.setText("0");
        }
        if(!jTNUM11_5.getText().equals("") ){
        	num[4] = Double.parseDouble(jTNUM11_5.getText());
        }else{
        	jTNUM11_5.setText("0");
        }
        
        if(!jTNUM11_6.getText().equals("") ){
        	num[5] = Double.parseDouble(jTNUM11_6.getText());
        }else{
        	jTNUM11_6.setText("0");
        }
        if(!jTNUM11_7.getText().equals("") ){
        	num[6] = Double.parseDouble(jTNUM11_7.getText());
        }else{
        	jTNUM11_7.setText("0");
        }
        
        if(!jTNUM11_8.getText().equals("") ){
        	num[7] = Double.parseDouble(jTNUM11_8.getText());
        }else{
        	jTNUM11_8.setText("0");
        }
        if(!jTNUM11_9.getText().equals("") ){
        	num[8] = Double.parseDouble(jTNUM11_9.getText());
        }else{
        	jTNUM11_9.setText("0");
        }
        
        if(!jTNUM11_10.getText().equals("") ){
        	num[9] = Double.parseDouble(jTNUM11_10.getText());
        }else{
        	jTNUM11_10.setText("0");
        }
        
        if(!jTNUM11_11.getText().equals("") ){
        	num[10] = Double.parseDouble(jTNUM11_11.getText());
        }else{
        	jTNUM11_11.setText("0");
        }
        
        if(!jTNUM11_12.getText().equals("") ){
        	num[11] = Double.parseDouble(jTNUM11_12.getText());
        }else{
        	jTNUM11_12.setText("0");
        }
        
        if(!jTNUM11_13.getText().equals("") ){
        	num[12] = Double.parseDouble(jTNUM11_13.getText());
        }else{
        	jTNUM11_13.setText("0");
        }
        
        if(!jTNUM11_14.getText().equals("") ){
        	num[13] = Double.parseDouble(jTNUM11_14.getText());
        }else{
        	jTNUM11_14.setText("0");
        }
        
        if(!jTNUM11_15.getText().equals("") ){
        	num[14] = Double.parseDouble(jTNUM11_15.getText());
        }else{
        	jTNUM11_15.setText("0");
        }
        
        if(!jTNUM11_16.getText().equals("") ){
        	num[15] = Double.parseDouble(jTNUM11_16.getText());
        }else{
        	jTNUM11_16.setText("0");
        }
        if(!jTNUM11_17.getText().equals("") ){
        	num[16] = Double.parseDouble(jTNUM11_17.getText());
        }else{
        	jTNUM11_17.setText("0");
        }
        
        if(!jTNUM11_18.getText().equals("") ){
        	num[17] = Double.parseDouble(jTNUM11_18.getText());
        }else{
        	jTNUM11_18.setText("0");
        }
        
        if(!jTNUM11_19.getText().equals("") ){
        	num[18] = Double.parseDouble(jTNUM11_19.getText());
        }else{
        	jTNUM11_19.setText("0");
        }
        if(!jTNUM11_20.getText().equals("") ){
        	num[19] = Double.parseDouble(jTNUM11_20.getText());
        }else{
        	jTNUM11_20.setText("0");
        }
        
        for(int i=0; i < 20; i++){
        	if(num[i] >= 18){
        		cont ++;
        	}
        	if(maior < num[i] ){
        		maior  = num[i];        		
        	}       
        }
        jTRESULTADO11_1.setText(String.valueOf(cont));
        jTRESULTADO11_2.setText(String.valueOf(maior));
    }
    /*fim exercicio 11*/
}





