/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.DAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Contatos_java;

/**
 *
 * @author X-E
 */
public final class Form_Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Form_Agenda
     */
    
    static DefaultTableModel modelo = new DefaultTableModel();
    private DAO dao;
    public Contatos_java contato;
    public Form_Agenda() {
        initComponents();          
        setColunasTabela();
        jTabela.setModel(modelo);
        inicioForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTNOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTTELEFONE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTEMAIL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTENDERECO = new javax.swing.JTextField();
        jTNUMERO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTBAIRRO = new javax.swing.JTextField();
        jTCIDADE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTESTADO = new javax.swing.JTextField();
        jTPAIS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTCELULAR = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jBNOVO = new javax.swing.JButton();
        jBADICIONAR = new javax.swing.JButton();
        jBSALVAR = new javax.swing.JButton();
        jBEDITAR = new javax.swing.JButton();
        jBDELETAR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTLINHASELECIONADA = new javax.swing.JTextField();
        jBRETORNA = new javax.swing.JButton();
        jBMAISREGISTRO = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Contato"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("ID:");

        jTID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("NOME: ");

        jTNOME.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTNOME.setNextFocusableComponent(jTTELEFONE);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("TELEFONE:");

        jTTELEFONE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTTELEFONE.setNextFocusableComponent(jTCELULAR);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CELULAR: ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("EMAIL: ");

        jTEMAIL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTEMAIL.setNextFocusableComponent(jTENDERECO);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("ENDEREÇO: ");

        jTENDERECO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTENDERECO.setNextFocusableComponent(jTNUMERO);

        jTNUMERO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTNUMERO.setNextFocusableComponent(jTBAIRRO);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("NUMERO:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("BAIRRO: ");

        jTBAIRRO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTBAIRRO.setNextFocusableComponent(jTCIDADE);

        jTCIDADE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTCIDADE.setNextFocusableComponent(jTESTADO);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("CIDADE:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("ESTADO: ");

        jTESTADO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTESTADO.setNextFocusableComponent(jTPAIS);

        jTPAIS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTPAIS.setNextFocusableComponent(jBNOVO);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("PAÍS: ");

        jTCELULAR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTCELULAR.setNextFocusableComponent(jTEMAIL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPAIS, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPAIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TEL", "CEL", "EMAIL", "ENDERECO", "NUM", "BAIRRO", "CIDADE", "ESTADO", "PAIS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTabelaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTabela);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));

        jBNOVO.setText("NOVO");
        jBNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNOVOActionPerformed(evt);
            }
        });

        jBADICIONAR.setText("ADICIONAR");
        jBADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBADICIONARActionPerformed(evt);
            }
        });

        jBSALVAR.setText("SALVAR");
        jBSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSALVARActionPerformed(evt);
            }
        });

        jBEDITAR.setText("EDITAR");
        jBEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEDITARActionPerformed(evt);
            }
        });

        jBDELETAR.setText("DELETAR");
        jBDELETAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDELETARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNOVO)
                .addGap(18, 18, 18)
                .addComponent(jBADICIONAR)
                .addGap(18, 18, 18)
                .addComponent(jBEDITAR)
                .addGap(18, 18, 18)
                .addComponent(jBSALVAR)
                .addGap(18, 18, 18)
                .addComponent(jBDELETAR)
                .addGap(103, 103, 103))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBADICIONAR, jBDELETAR, jBEDITAR, jBNOVO, jBSALVAR});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNOVO)
                    .addComponent(jBADICIONAR)
                    .addComponent(jBSALVAR)
                    .addComponent(jBEDITAR)
                    .addComponent(jBDELETAR))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTLINHASELECIONADA.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jTLINHASELECIONADA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jBRETORNA.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jBRETORNA.setText("<");
        jBRETORNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRETORNAActionPerformed(evt);
            }
        });

        jBMAISREGISTRO.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jBMAISREGISTRO.setText(">");
        jBMAISREGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMAISREGISTROActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRETORNA)
                .addGap(14, 14, 14)
                .addComponent(jTLINHASELECIONADA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBMAISREGISTRO)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBRETORNA, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTLINHASELECIONADA)
                        .addComponent(jBMAISREGISTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jBMAISREGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMAISREGISTROActionPerformed
        // TODO add your handling code here:
        PassaRegistro();
    }//GEN-LAST:event_jBMAISREGISTROActionPerformed

    private void jBDELETARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDELETARActionPerformed
        // TODO add your handling code here:
        Deletar();      
    }//GEN-LAST:event_jBDELETARActionPerformed

    private void jBNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNOVOActionPerformed
        // TODO add your handling code here:
        Novo();
    }//GEN-LAST:event_jBNOVOActionPerformed

    private void jBEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEDITARActionPerformed
        // TODO add your handling code here:        
        Editar();
    }//GEN-LAST:event_jBEDITARActionPerformed

    private void jBSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSALVARActionPerformed
        // TODO add your handling code here:
        Salvar();
    }//GEN-LAST:event_jBSALVARActionPerformed

    private void jBADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBADICIONARActionPerformed
        // TODO add your handling code here:
        Adicionar();
    }//GEN-LAST:event_jBADICIONARActionPerformed

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        // TODO add your handling code here:
        ClickTabela();
        getLinhaSelecionada();
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jTabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyPressed
        // TODO add your handling code here:
        ClickTabela();
        getLinhaSelecionada();
    }//GEN-LAST:event_jTabelaKeyPressed

    private void jTabelaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyTyped
        // TODO add your handling code here:
        ClickTabela();
        getLinhaSelecionada();
    }//GEN-LAST:event_jTabelaKeyTyped

    private void jTabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyReleased
        // TODO add your handling code here:
        ClickTabela();
        getLinhaSelecionada();
    }//GEN-LAST:event_jTabelaKeyReleased

    private void jBRETORNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRETORNAActionPerformed
        // TODO add your handling code here:
        RetornaRegistro();
    }//GEN-LAST:event_jBRETORNAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Agenda().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jBADICIONAR;
    private javax.swing.JButton jBDELETAR;
    private javax.swing.JButton jBEDITAR;
    private javax.swing.JButton jBMAISREGISTRO;
    private javax.swing.JButton jBNOVO;
    private javax.swing.JButton jBRETORNA;
    private javax.swing.JButton jBSALVAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTBAIRRO;
    private javax.swing.JTextField jTCELULAR;
    private javax.swing.JTextField jTCIDADE;
    private javax.swing.JTextField jTEMAIL;
    private javax.swing.JTextField jTENDERECO;
    private javax.swing.JTextField jTESTADO;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTLINHASELECIONADA;
    private javax.swing.JTextField jTNOME;
    private javax.swing.JTextField jTNUMERO;
    private javax.swing.JTextField jTPAIS;
    private javax.swing.JTextField jTTELEFONE;
    private javax.swing.JTable jTabela;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
    
    //Bloqueia as txtbox
    private void BloqueiaTxt(){        
        jTID.setEnabled(false);
        jTNOME.setEnabled(false);
	jTTELEFONE.setEnabled(false);
	jTCELULAR.setEnabled(false);
	jTEMAIL.setEnabled(false);
	jTENDERECO.setEnabled(false);
	jTNUMERO.setEnabled(false);
        jTBAIRRO.setEnabled(false);
        jTCIDADE.setEnabled(false);
	jTESTADO.setEnabled(false);
        jTPAIS.setEnabled(false);
    }
    //Desloqueia as txt box
    private void DesbloqueiaTxt(){
        //jTID.setEnabled(true);
        jTNOME.setEnabled(true);
	jTTELEFONE.setEnabled(true);
	jTCELULAR.setEnabled(true);
	jTEMAIL.setEnabled(true);
	jTENDERECO.setEnabled(true);
	jTNUMERO.setEnabled(true);
        jTBAIRRO.setEnabled(true);
        jTCIDADE.setEnabled(true);
	jTESTADO.setEnabled(true);
        jTPAIS.setEnabled(true);
    }
    //Limpa as txt box
    private void LimpaTxt(){
        jTID.setText("");
        jTNOME.setText("");
	jTTELEFONE.setText("");
	jTCELULAR.setText("");
	jTEMAIL.setText("");
	jTENDERECO.setText("");
	jTNUMERO.setText("");
        jTBAIRRO.setText("");
        jTCIDADE.setText("");
	jTESTADO.setText("");
        jTPAIS.setText("");    
    }
    
    private void setColunasTabela(){
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("TEL");
        modelo.addColumn("CEL");
        modelo.addColumn("EMAIL");
        modelo.addColumn("ENDEREÇO");
        modelo.addColumn("NUM");
        modelo.addColumn("BAIRO");
        modelo.addColumn("CIDADE");
        modelo.addColumn("ESTADO");
        modelo.addColumn("PAÍS");    
    }
    //
    public Contatos_java getTxtParaContato(){
        contato = new Contatos_java();
        //jTID.getText()
        int id;
        if(!jTID.getText().equals("") && !jTID.getText().equals(null) && !jTID.getText().equals(" ")){
            id = Integer.parseInt(jTID.getText());
        }else{
            id = 0;
        }
        contato.setId(id);
        contato.setNome(jTNOME.getText());
	contato.setTelefone(jTTELEFONE.getText());
	contato.setCelular(jTCELULAR.getText());
	contato.setEmail(jTEMAIL.getText());
	contato.setEndereco(jTENDERECO.getText());
	contato.setNumero(jTNUMERO.getText());
        contato.setBairro(jTBAIRRO.getText());
        contato.setCidade(jTCIDADE.getText());
	contato.setEstado(jTESTADO.getText());
        contato.setPais(jTPAIS.getText());    
        return contato;
    }
    public void TabelaParaTxt(){
        int linha = jTabela.getSelectedRow();
        if( linha != -1){
        jTID.setText(String.valueOf(modelo.getValueAt(linha, 0)));
        jTNOME.setText(String.valueOf(modelo.getValueAt(linha, 1)));
	jTTELEFONE.setText(String.valueOf(modelo.getValueAt(linha, 2)));
	jTCELULAR.setText(String.valueOf(modelo.getValueAt(linha, 3)));
	jTEMAIL.setText(String.valueOf(modelo.getValueAt(linha, 4)));
	jTENDERECO.setText(String.valueOf(modelo.getValueAt(linha, 5)));
	jTNUMERO.setText(String.valueOf(modelo.getValueAt(linha, 6)));
        jTBAIRRO.setText(String.valueOf(modelo.getValueAt(linha, 7)));
        jTCIDADE.setText(String.valueOf(modelo.getValueAt(linha, 8)));
	jTESTADO.setText(String.valueOf(modelo.getValueAt(linha, 9)));
        jTPAIS.setText(String.valueOf(modelo.getValueAt(linha, 10)));
        }else{
            //JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha da tabela para editar");
            jBEDITAR.setEnabled(false);
        }
        
    }
    
    public void limparTabela(){
        for(int l = modelo.getRowCount(); l > 0; l--){        
            modelo.removeRow(l -1);
        }        
    }
    public void AddLinhaTabela(){
        String linha[] = {"","","","","","","","","","","",};
            modelo.addRow(linha);                 
    }
    //Atualiza a dabela com as dados do banco de dados
    public void AtualizaTabela(){
        limparTabela();
        dao = new DAO();        
        List<Contatos_java> contatos = dao.getLista();
        for(int i = 0; i < (contatos.size()); i++){        
           AddLinhaTabela();           
           modelo.setValueAt(contatos.get(i).getId(), i, 0);           
           modelo.setValueAt(contatos.get(i).getNome(), i, 1);
           modelo.setValueAt(contatos.get(i).getTelefone(), i, 2);
           modelo.setValueAt(contatos.get(i).getCelular(), i, 3);
           modelo.setValueAt(contatos.get(i).getEmail(), i, 4);
           modelo.setValueAt(contatos.get(i).getEndereco(), i, 5);
           modelo.setValueAt(contatos.get(i).getNumero(), i, 6);
           modelo.setValueAt(contatos.get(i).getBairro(), i, 7);
           modelo.setValueAt(contatos.get(i).getCidade(), i, 8);
           modelo.setValueAt(contatos.get(i).getEstado(), i, 9);
           modelo.setValueAt(contatos.get(i).getPais(), i, 10);           
        }
    }
    public void Novo(){
        DesbloqueiaTxt();
        LimpaTxt();
        jBSALVAR.setEnabled(false);
        //jBEDITAR.setEnabled(false);
        jBDELETAR.setEnabled(false);
        jBADICIONAR.setEnabled(true);
    }
    public void Adicionar(){        
        dao = new DAO();  
        dao.setAdiciona(getTxtParaContato());
        JOptionPane.showMessageDialog(null, "Contato Adicionado com sucesso!!!");        
        inicioForm();
        int linha = jTabela.getSelectedRow();        
        linha = jTabela.getRowCount();        
        jTabela.setRowSelectionInterval((jTabela.getRowCount()-1), (jTabela.getRowCount()-1));
        TabelaParaTxt();
    }
    public void Editar(){                
        TabelaParaTxt();
        DesbloqueiaTxt();
        jBADICIONAR.setEnabled(true);
        jBSALVAR.setEnabled(true);
        jBADICIONAR.setEnabled(true);
        jBDELETAR.setEnabled(true);        
    }
    public void Salvar(){        
        dao = new DAO();  
        dao.setAtualiza(getTxtParaContato());
        JOptionPane.showMessageDialog(null, "Contato Atualizado com sucesso!!!");  
        inicioForm();
    }
    public void Deletar(){        
                          
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir contato?");
        if (resposta == JOptionPane.YES_OPTION) {
            // verifica se o usuário clicou no botão YES
            dao = new DAO();
            //Deleta contato
            dao.setDeleta(getTxtParaContato());
            JOptionPane.showMessageDialog(null, "Contato excluido com sucesso!!!");            
        } 
        inicioForm();
    }
    
    public void ClickTabela(){
        TabelaParaTxt();
        BloqueiaTxt();
        jBADICIONAR.setEnabled(false);
        jBSALVAR.setEnabled(false);
        jBADICIONAR.setEnabled(false);
        jBDELETAR.setEnabled(false);
    }
    
    private void getLinhaSelecionada(){
        int linha = jTabela.getSelectedRow();
        if (linha != -1){
            jTLINHASELECIONADA.setText(String.valueOf(linha+1));
        } 
    }     
    private void PassaRegistro(){
        int linha = jTabela.getSelectedRow();
        if (linha == -1){
            linha = 0;
        }
        if(linha < (jTabela.getRowCount()-1)){
            jTabela.setRowSelectionInterval(linha+1, linha+1);
        }
        if(linha >= (jTabela.getRowCount()-1)){
            jTabela.setRowSelectionInterval(0, 0);
        }           
            getLinhaSelecionada();
            ClickTabela();        
    }
    private void RetornaRegistro(){
        int linha = jTabela.getSelectedRow();
        if (linha == -1){
            linha = jTabela.getRowCount();
        }
        if(linha > 0 ){
            jTabela.setRowSelectionInterval(linha-1, linha-1);
        }
        if(linha == 0){
            jTabela.setRowSelectionInterval((jTabela.getRowCount()-1), (jTabela.getRowCount()-1));
        }           
            getLinhaSelecionada();
            ClickTabela();        
    }
    
    
    private void inicioForm(){
        BloqueiaTxt();
        jBADICIONAR.setEnabled(false);
        jBSALVAR.setEnabled(false);
        jBADICIONAR.setEnabled(false);
        jBDELETAR.setEnabled(false);        
        AtualizaTabela();                    
    }
}
