/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1323594
 */
public class Exercicio2 extends javax.swing.JFrame {

    static DefaultTableModel modelo = new DefaultTableModel();
    
    public Exercicio2() {
        initComponents();
        setColunasTabela();
        jTabela.setModel(modelo);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBEXECUTAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBADICIONAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null},
                {"2", null, null, null, null, null, null},
                {"3", null, null, null, null, null, null},
                {"4", null, null, null, null, null, null},
                {"5", null, null, null, null, null, null},
                {"6", null, null, null, null, null, null},
                {"7", null, null, null, null, null, null},
                {"8", null, null, null, null, null, null},
                {"9", null, null, null, null, null, null},
                {"10", null, null, null, null, null, null},
                {"11", null, null, null, null, null, null},
                {"12", null, null, null, null, null, null},
                {"13", null, null, null, null, null, null},
                {"14", null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ALUNO", "NOTA 1", "NOTA 2", "AULAS MINISTRADAS", "AULAS ASSISTIDAS", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        jBEXECUTAR.setText("EXECUTAR");
        jBEXECUTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXECUTARActionPerformed(evt);
            }
        });

        jLabel1.setText("DISCIPLINA: CÁUCULO");

        jBADICIONAR.setText("ADICIONAR");
        jBADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBADICIONARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 569, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBADICIONAR)
                .addGap(53, 53, 53)
                .addComponent(jBEXECUTAR)
                .addGap(243, 243, 243))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBADICIONAR, jBEXECUTAR});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEXECUTAR)
                    .addComponent(jBADICIONAR))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBADICIONARActionPerformed
        String linha[] = {String.valueOf(modelo.getRowCount()+1),"","","","","",""};
        if(modelo.getRowCount() < 16){
        modelo.addRow(linha);
        }
    }//GEN-LAST:event_jBADICIONARActionPerformed

    private void jBEXECUTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXECUTARActionPerformed
        executar();
    }//GEN-LAST:event_jBEXECUTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBADICIONAR;
    private javax.swing.JButton jBEXECUTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
private void setColunasTabela(){
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("NOTA1");
        modelo.addColumn("NOTA2");
        modelo.addColumn("AULAS MINISTRADAS");
        modelo.addColumn("AULAS ASSISTIDAS");
        modelo.addColumn("STATUS");        
    }
    
    private void executar(){
    float nota1,nota2,ministradas,assistidas,result;
    String status= "APROVADO";
    boolean verifica = true;
    
    for(int i = 0; i <modelo.getRowCount(); i++ ){
        nota1 = Float.parseFloat((String) modelo.getValueAt(i, 2));
        nota2 = Float.parseFloat((String) modelo.getValueAt(i, 3));
        ministradas = Float.parseFloat((String) modelo.getValueAt(i, 4));
        assistidas = Float.parseFloat((String) modelo.getValueAt(i, 5));        
        result = (nota1 + nota2) / 2;
        if(result <6){
            verifica = false;
        }
        result = (float) (ministradas * 0.75);
        if(assistidas < result){ 
            verifica = false;
        }
        if(verifica == false){
            status= "REPROVADO";
        }
        modelo.setValueAt(status,i, 6);        
    }
    
    //modelo.setValueAt(String.valueOf(modelo.getRowCount()), 0, 0);
    }
}
