/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author 1323594
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBEXERCICIO_1 = new javax.swing.JButton();
        jBEXERCICIO_2 = new javax.swing.JButton();
        jBEXERCICIO_3 = new javax.swing.JButton();
        jBEXERCICIO_4 = new javax.swing.JButton();
        jBEXERCICIO_8 = new javax.swing.JButton();
        jBEXERCICIO_5 = new javax.swing.JButton();
        jBEXERCICIO_6 = new javax.swing.JButton();
        jBEXERCICIO_7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBEXERCICIO_1.setText("EXERCICIO 1");
        jBEXERCICIO_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_1ActionPerformed(evt);
            }
        });

        jBEXERCICIO_2.setText("EXERCICIO 2");
        jBEXERCICIO_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_2ActionPerformed(evt);
            }
        });

        jBEXERCICIO_3.setText("EXERCICIO 3");
        jBEXERCICIO_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_3ActionPerformed(evt);
            }
        });

        jBEXERCICIO_4.setText("EXERCICIO 4");
        jBEXERCICIO_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_4ActionPerformed(evt);
            }
        });

        jBEXERCICIO_8.setText("EXERCICIO 8");
        jBEXERCICIO_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_8ActionPerformed(evt);
            }
        });

        jBEXERCICIO_5.setText("EXERCICIO 5");
        jBEXERCICIO_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_5ActionPerformed(evt);
            }
        });

        jBEXERCICIO_6.setText("EXERCICIO 6");
        jBEXERCICIO_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_6ActionPerformed(evt);
            }
        });

        jBEXERCICIO_7.setText("EXERCICIO 7");
        jBEXERCICIO_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEXERCICIO_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEXERCICIO_4)
                    .addComponent(jBEXERCICIO_3)
                    .addComponent(jBEXERCICIO_2)
                    .addComponent(jBEXERCICIO_1))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEXERCICIO_8)
                    .addComponent(jBEXERCICIO_7)
                    .addComponent(jBEXERCICIO_6)
                    .addComponent(jBEXERCICIO_5))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBEXERCICIO_1, jBEXERCICIO_2, jBEXERCICIO_3, jBEXERCICIO_4, jBEXERCICIO_5, jBEXERCICIO_6, jBEXERCICIO_7, jBEXERCICIO_8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEXERCICIO_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEXERCICIO_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEXERCICIO_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEXERCICIO_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEXERCICIO_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEXERCICIO_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEXERCICIO_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEXERCICIO_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEXERCICIO_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_1ActionPerformed
        Exercicio1 exercio = new Exercicio1();        
        exercio.setVisible(true);        
    }//GEN-LAST:event_jBEXERCICIO_1ActionPerformed

    private void jBEXERCICIO_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_2ActionPerformed
        Exercicio2 exercio = new Exercicio2();        
        exercio.setVisible(true);        
    }//GEN-LAST:event_jBEXERCICIO_2ActionPerformed

    private void jBEXERCICIO_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_3ActionPerformed
        Exercicio3 exercio = new Exercicio3();        
        exercio.setVisible(true);
    }//GEN-LAST:event_jBEXERCICIO_3ActionPerformed

    private void jBEXERCICIO_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_4ActionPerformed
        Exercicio4 exercio = new Exercicio4();        
        exercio.setVisible(true);
    }//GEN-LAST:event_jBEXERCICIO_4ActionPerformed

    private void jBEXERCICIO_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_5ActionPerformed
        Exercicio5 exercio = new Exercicio5();        
        exercio.setVisible(true);
    }//GEN-LAST:event_jBEXERCICIO_5ActionPerformed

    private void jBEXERCICIO_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_6ActionPerformed
        Exercicio6 exercio = new Exercicio6();        
        exercio.setVisible(true);
    }//GEN-LAST:event_jBEXERCICIO_6ActionPerformed

    private void jBEXERCICIO_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_7ActionPerformed
        Exercicio7 exercio = new Exercicio7();        
        exercio.setVisible(true);
    }//GEN-LAST:event_jBEXERCICIO_7ActionPerformed

    private void jBEXERCICIO_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEXERCICIO_8ActionPerformed
        Exercicio8 exercio = new Exercicio8();        
        exercio.setVisible(true);
    }//GEN-LAST:event_jBEXERCICIO_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEXERCICIO_1;
    private javax.swing.JButton jBEXERCICIO_2;
    private javax.swing.JButton jBEXERCICIO_3;
    private javax.swing.JButton jBEXERCICIO_4;
    private javax.swing.JButton jBEXERCICIO_5;
    private javax.swing.JButton jBEXERCICIO_6;
    private javax.swing.JButton jBEXERCICIO_7;
    private javax.swing.JButton jBEXERCICIO_8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
