/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;
import java.text.DecimalFormat;
import javax.naming.directory.SearchResult;
import javax.script.*;  

/**
 *
 * @author 1323594
 */
public class Calculadora extends javax.swing.JFrame {
        float memory;

        public Calculadora() {
        initComponents();
        jTVISOR.setText("");
        jTVISORMEMORY.setText("");
        jTVISORMEMORY.setEditable(false);
        memory = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTVISOR = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jBSOMA = new javax.swing.JButton();
        jBSUBTRACAO = new javax.swing.JButton();
        jBDIVISAO = new javax.swing.JButton();
        jBMULTIPLICACAO = new javax.swing.JButton();
        jBIGAUL = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jBMAISOUMENOS = new javax.swing.JButton();
        jBPONTO = new javax.swing.JButton();
        jBDIVISAO1 = new javax.swing.JButton();
        jBX2 = new javax.swing.JButton();
        jB1_X = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBBACKSPACE = new javax.swing.JButton();
        jBCLEAR = new javax.swing.JButton();
        jBCLEARALL = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBMC = new javax.swing.JButton();
        jBMR = new javax.swing.JButton();
        jBMS = new javax.swing.JButton();
        jBMMAIS = new javax.swing.JButton();
        jTVISORMEMORY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTVISOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTVISORActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jBSOMA.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBSOMA.setText("+");
        jBSOMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSOMAActionPerformed(evt);
            }
        });

        jBSUBTRACAO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBSUBTRACAO.setText("-");
        jBSUBTRACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSUBTRACAOActionPerformed(evt);
            }
        });

        jBDIVISAO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBDIVISAO.setText("/");
        jBDIVISAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDIVISAOActionPerformed(evt);
            }
        });

        jBMULTIPLICACAO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMULTIPLICACAO.setText("x");
        jBMULTIPLICACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMULTIPLICACAOActionPerformed(evt);
            }
        });

        jBIGAUL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBIGAUL.setText("=");
        jBIGAUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIGAULActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jBMAISOUMENOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMAISOUMENOS.setText("±");
        jBMAISOUMENOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMAISOUMENOSActionPerformed(evt);
            }
        });

        jBPONTO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBPONTO.setText(".");
        jBPONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPONTOActionPerformed(evt);
            }
        });

        jBDIVISAO1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBDIVISAO1.setText("Sqtr");
        jBDIVISAO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDIVISAO1ActionPerformed(evt);
            }
        });

        jBX2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBX2.setText("x ²");
        jBX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBX2ActionPerformed(evt);
            }
        });

        jB1_X.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB1_X.setText("1/x");
        jB1_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1_XActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBPONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMAISOUMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBDIVISAO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBDIVISAO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBSOMA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB1_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBSUBTRACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBIGAUL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBMULTIPLICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBX2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDIVISAO, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDIVISAO1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMULTIPLICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBX2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSOMA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB1_X, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMAISOUMENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBIGAUL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSUBTRACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBBACKSPACE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBBACKSPACE.setText("Backspace");
        jBBACKSPACE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBACKSPACEActionPerformed(evt);
            }
        });

        jBCLEAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCLEAR.setText("Clear");
        jBCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCLEARActionPerformed(evt);
            }
        });

        jBCLEARALL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCLEARALL.setText("Clear All");
        jBCLEARALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCLEARALLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBBACKSPACE, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCLEARALL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBACKSPACE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCLEARALL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBMC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMC.setText("MC");
        jBMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMCActionPerformed(evt);
            }
        });

        jBMR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMR.setText("MR");
        jBMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMRActionPerformed(evt);
            }
        });

        jBMS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMS.setText("MS");
        jBMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMSActionPerformed(evt);
            }
        });

        jBMMAIS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMMAIS.setText("M+");
        jBMMAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMMAISActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBMC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jBMS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMMAIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBMC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBMR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBMS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBMMAIS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTVISORMEMORY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTVISOR)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTVISOR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTVISORMEMORY, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTVISORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTVISORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTVISORActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTVISOR.setText(jTVISOR.getText() + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jTVISOR.setText(jTVISOR.getText() + "0");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jBMAISOUMENOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMAISOUMENOSActionPerformed
        
         String s = jTVISOR.getText();          
            if (s.length() > 0) {  
                s = s.substring (0,1); 
                if (!s.equals("-")){
                    jTVISOR.setText("-" + jTVISOR.getText());
                }
                else{
                    String concat =jTVISOR.getText();
                    concat = concat.substring (1,concat.length());
                    jTVISOR.setText(concat);                    
                }
            }  
            
    }//GEN-LAST:event_jBMAISOUMENOSActionPerformed

    private void jBSOMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSOMAActionPerformed
        jTVISOR.setText(jTVISOR.getText() + " + ");
    }//GEN-LAST:event_jBSOMAActionPerformed

    private void jBSUBTRACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSUBTRACAOActionPerformed
        jTVISOR.setText(jTVISOR.getText() + " - ");
    }//GEN-LAST:event_jBSUBTRACAOActionPerformed

    private void jBMULTIPLICACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMULTIPLICACAOActionPerformed
        jTVISOR.setText(jTVISOR.getText() + " * ");
    }//GEN-LAST:event_jBMULTIPLICACAOActionPerformed

    private void jBDIVISAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDIVISAOActionPerformed
        jTVISOR.setText(jTVISOR.getText() + " / ");
    }//GEN-LAST:event_jBDIVISAOActionPerformed

    private void jBIGAULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIGAULActionPerformed
        ScriptEngineManager sem = new ScriptEngineManager();  
        ScriptEngine se = sem.getEngineByName( "javascript" );  
        String nparse = jTVISOR.getText();  
        String mostra = jTVISOR.getText();        
        //String  formate ="0";
        //verifica decimal
        //if (mostra.indexOf(".") >= 0)   {                    
          //  formate = "#.00";
        //}                        
                
        try {    
            String r = String.valueOf( se.eval( nparse ) );  
            float result = Float.parseFloat( r );             
            //DecimalFormat df = new DecimalFormat(formate);
            //mostra = String.valueOf(df.format(result));//formata casas decimais            
            mostra = String.valueOf(result);
            jTVISOR.setText(mostra);//exibe operação no visor  
        } catch ( ScriptException exc ) {  
            exc.printStackTrace();  
        }         

    }//GEN-LAST:event_jBIGAULActionPerformed

    private void jBPONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPONTOActionPerformed
         jTVISOR.setText(jTVISOR.getText() + ".");
    }//GEN-LAST:event_jBPONTOActionPerformed

    private void jBBACKSPACEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBACKSPACEActionPerformed
        String s = jTVISOR.getText();          
            if (s.length() > 0) {  
                s = s.substring (0, s.length() - 1);  
            }  
            jTVISOR.setText(s);
    }//GEN-LAST:event_jBBACKSPACEActionPerformed

    private void jBDIVISAO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDIVISAO1ActionPerformed
        //Math.sqrt(0)
        ScriptEngineManager sem = new ScriptEngineManager();  
        ScriptEngine se = sem.getEngineByName( "javascript" );          
        String nparse = "Math.sqrt("+jTVISOR.getText()+");";//jTVISOR.getText();  
        String mostra = jTVISOR.getText();                      
        try {    
            String r = String.valueOf( se.eval( nparse ) );  
            float result = Float.parseFloat( r );                        
            mostra =r;
            jTVISOR.setText(mostra);//exibe operação no visor  
        } catch ( ScriptException exc ) {  
            exc.printStackTrace();  
        }         
    }//GEN-LAST:event_jBDIVISAO1ActionPerformed

    private void jBX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBX2ActionPerformed
        ScriptEngineManager sem = new ScriptEngineManager();  
        ScriptEngine se = sem.getEngineByName( "javascript" );  
        String nparse = "Math.pow("+jTVISOR.getText()+", 2);";//jTVISOR.getText();  
        String mostra = jTVISOR.getText();        
        //String  formate ="0";
        //verifica decimal
        //if (mostra.indexOf(".") >= 0)   {                    
          //  formate = "#.00";
        //}                        
                
        try {    
            String r = String.valueOf( se.eval( nparse ) );  
            float result = Float.parseFloat( r );             
            //DecimalFormat df = new DecimalFormat(formate);
            //mostra = String.valueOf(df.format(result));//formata casas decimais            
            mostra = String.valueOf(result);
            jTVISOR.setText(mostra);//exibe operação no visor  
        } catch ( ScriptException exc ) {  
            exc.printStackTrace();  
        }         
    }//GEN-LAST:event_jBX2ActionPerformed

    private void jB1_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1_XActionPerformed
        ScriptEngineManager sem = new ScriptEngineManager();  
        ScriptEngine se = sem.getEngineByName( "javascript" );  
        String nparse = "1/"+jTVISOR.getText();  
        String mostra = jTVISOR.getText();        
       // String  formate ="0";
        //verifica decimal
       // if (mostra.indexOf(".") >= 0)   {                    
            //formate = "0.00";
        //}                        
                
        try {    
            String r = String.valueOf( se.eval( nparse ) );  
            float result = Float.parseFloat( r );             
            //DecimalFormat df = new DecimalFormat(formate);
            //mostra = String.valueOf(df.format(result));//formata casas decimais            
            mostra = String.valueOf(result);
            jTVISOR.setText(mostra);//exibe operação no visor  
        } catch ( ScriptException exc ) {  
            exc.printStackTrace();  
        }         
    }//GEN-LAST:event_jB1_XActionPerformed

    private void jBCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCLEARActionPerformed
         jTVISOR.setText("");
         jTVISORMEMORY.setText("");
    }//GEN-LAST:event_jBCLEARActionPerformed

    private void jBCLEARALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCLEARALLActionPerformed
        jTVISOR.setText("");
        jTVISORMEMORY.setText("");
    }//GEN-LAST:event_jBCLEARALLActionPerformed

    private void jBMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMCActionPerformed
        memory = 0;
        jTVISORMEMORY.setText("");
    }//GEN-LAST:event_jBMCActionPerformed

    private void jBMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMRActionPerformed
        jTVISORMEMORY.setText("M");        
        String mostra = String.valueOf(memory);        
       // String  formate ="0";
        //verifica decimal
       // if (mostra.indexOf(".") >= 0)   {                    
        //    formate = "#.00";
        //}            
            float result = memory;             
            //DecimalFormat df = new DecimalFormat(formate);
           // mostra = String.valueOf(df.format(memory));//formata casas decimais  
        mostra = String.valueOf(result);
            jTVISOR.setText(mostra);//exibe operação no visor  
            
                
    }//GEN-LAST:event_jBMRActionPerformed

    private void jBMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMSActionPerformed
        jTVISORMEMORY.setText("M");
        ScriptEngineManager sem = new ScriptEngineManager();  
        ScriptEngine se = sem.getEngineByName( "javascript" );  
        String nparse = jTVISOR.getText();  
        String mostra = jTVISOR.getText();        
       // String  formate ="0";
        //verifica decimal
       // if (mostra.indexOf(".") >= 0)   {                    
       //     formate = "#.00";
       // }                        
                
        try {    
            String r = String.valueOf( se.eval( nparse ) );  
            float result = Float.parseFloat( r );             
            //DecimalFormat df = new DecimalFormat(formate);
            //mostra = String.valueOf(df.format(result));//formata casas decimais   
            mostra = String.valueOf(result);
            jTVISOR.setText(mostra);//exibe operação no visor  
            memory = result;
        } catch ( ScriptException exc ) {  
            exc.printStackTrace();  
        }         
    }//GEN-LAST:event_jBMSActionPerformed

    private void jBMMAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMMAISActionPerformed
       jTVISORMEMORY.setText("M");
        ScriptEngineManager sem = new ScriptEngineManager();  
        ScriptEngine se = sem.getEngineByName( "javascript" );  
        String nparse = jTVISOR.getText();  
        String mostra = jTVISOR.getText();        
        //String  formate ="0";
        //verifica decimal
        //if (mostra.indexOf(".") >= 0)   {                    
          //  formate = "#.00";
        //}                        
                
        try {    
            String r = String.valueOf( se.eval( nparse ) );  
            float result = Float.parseFloat( r );             
           // DecimalFormat df = new DecimalFormat(formate);
            //mostra = String.valueOf(df.format(result));//formata casas decimais            
            mostra = String.valueOf(result);
            jTVISOR.setText(mostra);//exibe operação no visor  
            memory = memory + result;
        } catch ( ScriptException exc ) {  
            exc.printStackTrace();  
        }                        
    }//GEN-LAST:event_jBMMAISActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1_X;
    private javax.swing.JButton jBBACKSPACE;
    private javax.swing.JButton jBCLEAR;
    private javax.swing.JButton jBCLEARALL;
    private javax.swing.JButton jBDIVISAO;
    private javax.swing.JButton jBDIVISAO1;
    private javax.swing.JButton jBIGAUL;
    private javax.swing.JButton jBMAISOUMENOS;
    private javax.swing.JButton jBMC;
    private javax.swing.JButton jBMMAIS;
    private javax.swing.JButton jBMR;
    private javax.swing.JButton jBMS;
    private javax.swing.JButton jBMULTIPLICACAO;
    private javax.swing.JButton jBPONTO;
    private javax.swing.JButton jBSOMA;
    private javax.swing.JButton jBSUBTRACAO;
    private javax.swing.JButton jBX2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTVISOR;
    private javax.swing.JTextField jTVISORMEMORY;
    // End of variables declaration//GEN-END:variables
}
